require('devheshmati.config.telescope')
require('devheshmati.config.comment')
require('devheshmati.config.theme')
require('devheshmati.config.nvim-tree')
require('devheshmati.config.nvim-web-devicons')
require('devheshmati.config.nvim-surround')
require('devheshmati.config.treesitter')
-- require('devheshmati.config.bufferline')
require('devheshmati.config.colorizer')
require('devheshmati.config.autopairs')
require('devheshmati.config.indent-blankline')
require('devheshmati.config.lualine')
require('devheshmati.config.autocmd')
-- require('devheshmati.config.luasnip')
-- require('devheshmati.config.tabnine')
-- require('devheshmati.config.tmux-navigator')

-- lsp
require('devheshmati.config.lsp.lspconfig')
require('devheshmati.config.lsp.mason')
require('devheshmati.config.lsp.null-ls')
require('devheshmati.config.lsp.cmp')
require('devheshmati.config.lsp.lspkind')
