require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.neoscroll")
require("plugins.conform")
require("plugins.mason")
require("plugins.mason-conform")
require("plugins.treesitter")
-- require("plugins.comment")
require("plugins.tsc")
